// Real photos for a video's image slots.
//   node images.mjs ../VIDEO          -> VIDEO/images.js from the files in VIDEO/images/
//   node images.mjs ../VIDEO --list   -> also (re)writes VIDEO/images/README.md listing every slot
// A file's name without extension is its slot, e.g. images/texture-handhewn.jpg fills
// "texture-handhewn". Slots with no file keep the drawn illustration.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const dir = path.resolve(process.argv[2] || '.');
const imgDir = path.join(dir, 'images');
fs.mkdirSync(imgDir, { recursive: true });
const map = {};
for (const f of fs.readdirSync(imgDir).sort()) if (/\.(jpe?g|png|webp)$/i.test(f)) map[f.replace(/\.[^.]+$/, '')] = `images/${f}`;
fs.writeFileSync(path.join(dir, 'images.js'), `// Generated by shared/images.mjs: real photos for the video's image slots.\nwindow.IMAGES = ${JSON.stringify(map, null, 1)};\n`);
console.log(`${Object.keys(map).length} photo(s) -> ${path.join(dir, 'images.js')}`);

if (process.argv.includes('--list')) {
  const require = createRequire(import.meta.url);
  let chromium; try { ({ chromium } = require('playwright')); } catch { ({ chromium } = require(path.join(process.env.NODE_PATH || '/opt/node22/lib/node_modules', 'playwright'))); }
  const b = await chromium.launch(); const p = await b.newPage();
  await p.goto(pathToFileURL(path.join(dir, 'index.html')).href + '?render');
  const slots = await p.evaluate(async () => { for (let t = 0; t < window.__TOTAL; t += 0.5) window.__seek(t); return [...window.__slots]; });
  await b.close();
  const where = await (async () => slots)();
  const lines = ['# Image slots', '',
    'Drop a product photo in this folder named after its slot (`.jpg`, `.png` or `.webp`),',
    'then from `training/shared` run `node images.mjs ../<video-folder>` and re-render.',
    'A slot with no photo keeps its drawn illustration. Use real Ekena product photography only.', '',
    '| Slot | Has photo |', '|---|---|',
    ...where.map(s => `| \`${s}\` | ${map[s] ? 'yes' : ''} |`)];
  fs.writeFileSync(path.join(imgDir, 'README.md'), lines.join('\n') + '\n');
  console.log(`${where.length} slots listed in ${path.join(imgDir, 'README.md')}`);
}
