"""Build the narration track for a code-built training video.

The narration says exactly what the on-screen captions say (the fact-checked text in the
video's index.html); only the *spoken* form changes, per the video's lexicon.json:
  "say": [[regex, replacement], ...]  written form -> spoken form, applied in order
  "ipa": [[wrong, right, note], ...]  phoneme fixes for names the voice mispronounces

Each caption is synthesised separately. If a line needs more time than its caption slot,
the slot is stretched (the speech is never rushed); vo-timing.js tells index.html to
stretch the animation inside that slot by the same amount, so every reveal stays on its
sentence.

Usage (Kokoro TTS, open-weight, runs offline):
  node captions.mjs ../VIDEO captions.json
  python voiceover.py --dir ../VIDEO --captions captions.json --model kokoro-v1.0.onnx --voices voices-v1.0.bin
Writes into --dir: vo-timing.js, voiceover.wav, VOICEOVER_SCRIPT.md
"""
import argparse, json, re
from pathlib import Path

SR = 24000
LEAD, TAIL = 0.30, 0.55          # silence before / after each line inside its slot (s)


def load_lexicon(d: Path) -> dict:
    return json.loads((Path(d) / "lexicon.json").read_text())


def spoken(text: str, lex: dict) -> str:
    for a, b in lex.get("say", []):
        text = re.sub(a, b, text)
    return re.sub(r"(?<!\w)'|'(?!\w)", "", text)          # quote marks, not apostrophes


def phonemes(k, say: str, lex: dict) -> str:
    ph = k.tokenizer.phonemize(say, "en-us")
    for bad, good, *_ in lex.get("ipa", []):
        ph = ph.replace(bad, good)
    return ph


def main():
    import numpy as np
    import soundfile as sf
    from kokoro_onnx import Kokoro

    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", required=True, help="video folder (holds index.html and lexicon.json)")
    ap.add_argument("--captions", required=True)
    ap.add_argument("--model", required=True)
    ap.add_argument("--voices", required=True)
    ap.add_argument("--speed", type=float, default=1.0)
    a = ap.parse_args()
    out = Path(a.dir)
    lex = load_lexicon(out)
    voice = lex.get("voice", "af_heart")
    caps = json.load(open(a.captions))
    k = Kokoro(a.model, a.voices)

    clips, rows = [], []
    for c in caps:
        say = spoken(c["text"], lex)
        audio, sr = k.create(phonemes(k, say, lex), voice=voice, speed=a.speed, is_phonemes=True)
        assert sr == SR
        dur = len(audio) / SR
        slot = c["end"] - c["start"]
        clips.append(audio)
        rows.append(dict(c, say=say, speech=round(dur, 3), newDur=round(max(slot, LEAD + dur + TAIL), 3)))

    t = 0.0
    for r in rows:                                   # cue i starts where cue i-1 ends
        r["newStart"] = round(t, 3)
        t += r["newDur"]
    total = t
    track = np.zeros(int((total + 1) * SR), dtype=np.float32)
    for r, clip in zip(rows, clips):
        i = int((r["newStart"] + LEAD) * SR)
        track[i:i + len(clip)] += clip
    track *= 0.89 / (float(np.max(np.abs(track))) or 1.0)    # about -1 dBFS peak
    sf.write(out / "voiceover.wav", track[: int(total * SR)], SR)

    timing = [dict(origStart=r["start"], origEnd=r["end"], newStart=r["newStart"], newDur=r["newDur"]) for r in rows]
    (out / "vo-timing.js").write_text(
        "// Generated by shared/voiceover.py: caption slots re-timed to fit the narration.\n"
        f"window.VO_TIMING = {json.dumps(timing)};\n")

    def mmss(s): return f"{int(s // 60)}:{s % 60:04.1f}"
    md = [f"# {lex.get('video', 'Training video')}: voiceover script", "",
          f"Voice: Kokoro `{voice}`, speed {a.speed}. Total runtime {mmss(total)}. "
          "Generated by `shared/voiceover.py`; the spoken text is the on-screen caption, "
          "rewritten only where pronunciation needs it.", ""]
    if lex.get("pronounce"):
        md += ["Pronunciations to confirm: " + "; ".join(f"**{w}** = {p}" for w, p in lex["pronounce"].items()), ""]
    chap = None
    for r in rows:
        if r["chapter"] != chap:
            chap = r["chapter"]; md += ["", f"## {r['scene']:02d} · {chap}", ""]
        md.append(f"**{mmss(r['newStart'])}** {r['text']}")
        if r["say"] != r["text"]:
            md.append(f"  *spoken as:* {r['say']}")
        md.append("")
    (out / "VOICEOVER_SCRIPT.md").write_text("\n".join(md))
    stretched = sum(1 for r in rows if r["newDur"] > r["end"] - r["start"] + 1e-6)
    print(f"{len(rows)} lines, {stretched} slots stretched, runtime {mmss(total)} (was {mmss(caps[-1]['end'])})")


if __name__ == "__main__":
    main()
